<%@ page language="java" import="java.util.*" pageEncoding="utf-8" isELIgnored="false"%>
<%
String path = request.getContextPath();
%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<style type="text/css">
	.img-div{
		min-height: 701px;
		width: 100%;
		height: 100%;
	}
	.img-div .index-top-bg{
		width: 100%;
		height: 100%;
	}
	.img-div .text-div{
		width:100%;
		position:absolute;
		top:60px;
		z-index:99;
	}
	.img-div .text-div .text-content{
		position:relative;
		width:1024px;
		margin: auto;
	}
	.img-div .text-div .text-content .product-div{
		vertical-align:middle;
		font-family: Helvetica, Tahoma, Arial, "Hiragino Sans GB", "Hiragino Sans GB W3", "Microsoft YaHei", STXihei, STHeiti, Heiti, SimSun, sans-serif;
		color:white;
		margin-top:100px;
		width:400px;
	}
	.img-div .text-div .text-content .introduce-img{
		position: absolute;
		top:50%;
		left: 100%;
		width: 600px;
		height: 400px;
		margin-left: -600px;
		margin-top: -200px;
		border-radius:2px;
	}
	.img-div .text-div .text-content .product-div a{
		display:inline-block;
		width:200px;
		margin:0px 50px;
		height:30px;
		line-height:30px;
		text-align:center;
		color:rgba(42, 196, 254,1);
		font-weight:bold;
		background:rgba(255,255, 255,0.9);
		border-radius:15px;
	}
	.content-div{
		width: 100%;
		min-height:600px;
	}

	.content-div .bg-div{
		min-height:600px;
		width: 100%;
		height: 100%;
	}
	.content-div .bg-div img{
		width: 100%;
		height: 100%;

	}
	.content-div .message-div{
		background-color:white;
		height:100%;
		min-height:600px;
		width:100%;
	}
	.content-div .message-div .message-center{
		width: 1024px;
		margin: auto;
		font-family: Helvetica, Tahoma, Arial, "Hiragino Sans GB", "Hiragino Sans GB W3", "Microsoft YaHei", STXihei, STHeiti, Heiti, SimSun, sans-serif;
	}
	.content-div .message-div .message-text{
		width: 50%;
		float: left;
	}
	.content-div .message-div .message-text .message-title{
		font-size: 50px;
		line-height:80px;
	}
	.content-div .message-div .message-text .message-content{
		color: rgba(127, 150, 182,1);
	}
	.content-div .message-div .message-text .message-content a{
		color: rgba(97, 197, 253,1);
		line-height: 30px;
	}
	.content-div .message-div .message-text .message-others{

	}
	.content-div .message-div .message-img{
		width: 50%;
		height:340px;
		float: right;
		text-align: center;
	}
	.content-div .message-div .message-img img{
		margin:10%;
		width: 80%;
		height: 80%;
		border-radius: 10px;
	}
</style>
<script type="text/javascript" src="<%=path%>/static/js/indexDivJs.js" async></script>
</head>
<body>
	<div class="img-div">
		<img class="index-top-bg" alt=""
			src="<%=path%>/static/img/webp/index_top_bg.webp">
		<div class="text-div">
			<div class="text-content">
				<div class="product-div">
					<div class="product-info">
						<p>HMDM is the master data management platform developed by
							HAND in order to meet the needs of unified management of master
							data. It aims to help enterprises solve the information island
							problem with new technical methods.</p>
						<p>Based on the HAP framework of HAND, the integration of
							Spring, Spring MVC, MyBatis and other open source technologies,
							using REST, SOA micro-service architecture, through Maven,
							Liquibase, Jenkins technology to achieve cross-platform, cross
							DB, continuous deployment</p>
						<p>The use of load balancing, reverse proxy, server cluster,
							database master-slave replication, cache, Zookeeper and other
							technologies, the system using WebService, ESB, MQ and other
							technologies to achieve data exchange between systems</p>
					</div>
					<a href="javascript:void(0);">DownLoad</a>
				</div>
				<img class="introduce-img" src="<%=path%>/static/img/home_HMDM_introduce.jpg">
			</div>
		</div>
	</div>

	<div class="content-div">
		<div class="bg-div">
			<img class="lazy-loaded" url="<%=path%>/static/img/webp/index_test_bg.webp">
		</div>
		<div class="message-div">
			<div class="message-center">
				<div class="message-text">
					<div class="message-title">Master Data Definition</div>
					<div class="message-content">
						<div>
							<p>HMDM can manage any type of master data according to enterprise management needs, business needs, system integration needs, including but not limited to: customer, vendor, project, mater, account, organization, staff, price, etc.</p>
							<p>The system administrator can customize the master data type, classification, attribute, attribute value set in HMDM, etc.</p>
							<p>Custom Encoder: The system administrator can customize the encoding and description rules, the system automatically generated by the rules of coding or description</p>
							<p>Pre-configured data attributes: Pre-configured data attributes for ORACEL EBS, SAP ECC</p>
						</div>
						<a href="javascript:void(0);">More+</a>
					</div>
					<div class="message-others"></div>
				</div>
				<div class="message-img">
					<img class="lazy-loaded" url="<%=path%>/static/img/index_test_bg2.jpg">
				</div>
			</div>
		</div>
	</div>
	<div class="content-div">
		<div class="bg-div">
			<img class="lazy-loaded" url="<%=path%>/static/img/webp/index_test_bg.webp">
		</div>
		<div class="message-div">
			<div class="message-center">
				<div class="message-text">
					<div class="message-title">Master Data Definition</div>
					<div class="message-content">
						<div>
							<p>HMDM can manage any type of master data according to enterprise management needs, business needs, system integration needs, including but not limited to: customer, vendor, project, mater, account, organization, staff, price, etc.</p>
							<p>The system administrator can customize the master data type, classification, attribute, attribute value set in HMDM, etc.</p>
							<p>Custom Encoder: The system administrator can customize the encoding and description rules, the system automatically generated by the rules of coding or description</p>
							<p>Pre-configured data attributes: Pre-configured data attributes for ORACEL EBS, SAP ECC</p>
						</div>
						<a href="javascript:void(0);">More+</a>
					</div>
					<div class="message-others"></div>
				</div>
				<div class="message-img">
					<img class="lazy-loaded" url="<%=path%>/static/img/index_test_bg2.jpg">
				</div>
			</div>
		</div>
	</div>
</body>
</html>

