package hmdm.mapper;

import hmdm.dto.DownRecord;
import hmdm.dto.DownRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DownRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_downrecord
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    long countByExample(DownRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_downrecord
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    int deleteByExample(DownRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_downrecord
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_downrecord
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    int insert(DownRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_downrecord
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    int insertSelective(DownRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_downrecord
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    List<DownRecord> selectByExample(DownRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_downrecord
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    DownRecord selectByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_downrecord
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") DownRecord record, @Param("example") DownRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_downrecord
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    int updateByExample(@Param("record") DownRecord record, @Param("example") DownRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_downrecord
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(DownRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_downrecord
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    int updateByPrimaryKey(DownRecord record);
}