package hmdm.mapper;

import hmdm.dto.Employee;
import hmdm.dto.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_employee
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_employee
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_employee
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Long employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_employee
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_employee
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_employee
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_employee
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    Employee selectByPrimaryKey(Long employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_employee
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_employee
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_employee
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_employee
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    int updateByPrimaryKey(Employee record);

    List<String> selectNameByFunctionId(Long functionId);
}