package hmdm.mapper;

import hmdm.dto.Function;
import hmdm.dto.FunctionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FunctionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_product_function
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	long countByExample(FunctionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_product_function
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int deleteByExample(FunctionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_product_function
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Long functionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_product_function
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int insert(Function record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_product_function
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int insertSelective(Function record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_product_function
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	List<Function> selectByExample(FunctionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_product_function
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	Function selectByPrimaryKey(Long functionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_product_function
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") Function record, @Param("example") FunctionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_product_function
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") Function record, @Param("example") FunctionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_product_function
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(Function record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_product_function
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int updateByPrimaryKey(Function record);

	List<Function> selectByProductId(Long productId);
}