package hmdm.mapper;

import hmdm.dto.State;
import hmdm.dto.StateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_productstate
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	long countByExample(StateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_productstate
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int deleteByExample(StateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_productstate
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Integer stateId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_productstate
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int insert(State record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_productstate
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int insertSelective(State record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_productstate
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	List<State> selectByExample(StateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_productstate
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	State selectByPrimaryKey(Integer stateId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_productstate
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") State record, @Param("example") StateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_productstate
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") State record, @Param("example") StateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_productstate
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(State record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_productstate
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int updateByPrimaryKey(State record);
}