package hmdm.mapper;

import hmdm.dto.SuggestInfo;
import hmdm.dto.SuggestInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SuggestInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_info
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	long countByExample(SuggestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_info
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int deleteByExample(SuggestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_info
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Long suggestId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_info
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int insert(SuggestInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_info
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int insertSelective(SuggestInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_info
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	List<SuggestInfo> selectByExample(SuggestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_info
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	SuggestInfo selectByPrimaryKey(Long suggestId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_info
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") SuggestInfo record, @Param("example") SuggestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_info
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") SuggestInfo record, @Param("example") SuggestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_info
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(SuggestInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_info
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	int updateByPrimaryKey(SuggestInfo record);

	Long lastInsertId();
}