package hmdm.dto;

public class Customer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_customer.customer_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private Long customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_customer.name
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_customer.email
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_customer.password
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_customer.customer_id
	 * @return  the value of hmdm_pt_customer.customer_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public Long getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_customer.customer_id
	 * @param customerId  the value for hmdm_pt_customer.customer_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_customer.name
	 * @return  the value of hmdm_pt_customer.name
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_customer.name
	 * @param name  the value for hmdm_pt_customer.name
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_customer.email
	 * @return  the value of hmdm_pt_customer.email
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_customer.email
	 * @param email  the value for hmdm_pt_customer.email
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_customer.password
	 * @return  the value of hmdm_pt_customer.password
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_customer.password
	 * @param password  the value for hmdm_pt_customer.password
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public String toString() {
		return "Customer{" +
				"customerId=" + customerId +
				", name='" + name + '\'' +
				", email='" + email + '\'' +
				", password='" + password + '\'' +
				'}';
	}
}