package hmdm.dto;

import java.util.Date;

public class DownRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmdm_pt_downrecord.record_id
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    private Long recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmdm_pt_downrecord.customer_id
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmdm_pt_downrecord.product_id
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmdm_pt_downrecord.time
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmdm_pt_downrecord.record_id
     *
     * @return the value of hmdm_pt_downrecord.record_id
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    public Long getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmdm_pt_downrecord.record_id
     *
     * @param recordId the value for hmdm_pt_downrecord.record_id
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmdm_pt_downrecord.customer_id
     *
     * @return the value of hmdm_pt_downrecord.customer_id
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmdm_pt_downrecord.customer_id
     *
     * @param customerId the value for hmdm_pt_downrecord.customer_id
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmdm_pt_downrecord.product_id
     *
     * @return the value of hmdm_pt_downrecord.product_id
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmdm_pt_downrecord.product_id
     *
     * @param productId the value for hmdm_pt_downrecord.product_id
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmdm_pt_downrecord.time
     *
     * @return the value of hmdm_pt_downrecord.time
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmdm_pt_downrecord.time
     *
     * @param time the value for hmdm_pt_downrecord.time
     *
     * @mbg.generated Wed Aug 09 11:45:39 GMT+08:00 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }
}