package hmdm.dto;

import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_employee.employee_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    private Long employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_employee.name
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_employee.email
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_employee.phone
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_employee.password
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_employee.join_date
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    private Date joinDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_employee.gender
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_employee.function_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    private Long functionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_employee.employee_id
     *
     * @return the value of hr_employee.employee_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_employee.employee_id
     *
     * @param employeeId the value for hr_employee.employee_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_employee.name
     *
     * @return the value of hr_employee.name
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_employee.name
     *
     * @param name the value for hr_employee.name
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_employee.email
     *
     * @return the value of hr_employee.email
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_employee.email
     *
     * @param email the value for hr_employee.email
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_employee.phone
     *
     * @return the value of hr_employee.phone
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_employee.phone
     *
     * @param phone the value for hr_employee.phone
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_employee.password
     *
     * @return the value of hr_employee.password
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_employee.password
     *
     * @param password the value for hr_employee.password
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_employee.join_date
     *
     * @return the value of hr_employee.join_date
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_employee.join_date
     *
     * @param joinDate the value for hr_employee.join_date
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_employee.gender
     *
     * @return the value of hr_employee.gender
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_employee.gender
     *
     * @param gender the value for hr_employee.gender
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_employee.function_id
     *
     * @return the value of hr_employee.function_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public Long getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_employee.function_id
     *
     * @param functionId the value for hr_employee.function_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setFunctionId(Long functionId) {
        this.functionId = functionId;
    }
}