package hmdm.dto;

public class Function {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_product_function.function_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private Long functionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_product_function.function_name
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String functionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_product_function.product_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private Long productId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_product_function.function_id
	 * @return  the value of hmdm_pt_product_function.function_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public Long getFunctionId() {
		return functionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_product_function.function_id
	 * @param functionId  the value for hmdm_pt_product_function.function_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setFunctionId(Long functionId) {
		this.functionId = functionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_product_function.function_name
	 * @return  the value of hmdm_pt_product_function.function_name
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getFunctionName() {
		return functionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_product_function.function_name
	 * @param functionName  the value for hmdm_pt_product_function.function_name
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_product_function.product_id
	 * @return  the value of hmdm_pt_product_function.product_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_product_function.product_id
	 * @param productId  the value for hmdm_pt_product_function.product_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}
}