package hmdm.dto;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_role.role_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_role.role_name
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_role.role_description
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String roleDescription;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_role.role_id
	 * @return  the value of hmdm_pt_role.role_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_role.role_id
	 * @param roleId  the value for hmdm_pt_role.role_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_role.role_name
	 * @return  the value of hmdm_pt_role.role_name
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_role.role_name
	 * @param roleName  the value for hmdm_pt_role.role_name
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_role.role_description
	 * @return  the value of hmdm_pt_role.role_description
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getRoleDescription() {
		return roleDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_role.role_description
	 * @param roleDescription  the value for hmdm_pt_role.role_description
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}
}