package hmdm.dto;

public class State {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_productstate.state_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private Integer stateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_productstate.name
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_productstate.state_id
	 * @return  the value of hmdm_pt_productstate.state_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public Integer getStateId() {
		return stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_productstate.state_id
	 * @param stateId  the value for hmdm_pt_productstate.state_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_productstate.name
	 * @return  the value of hmdm_pt_productstate.name
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_productstate.name
	 * @param name  the value for hmdm_pt_productstate.name
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setName(String name) {
		this.name = name;
	}
}