package hmdm.dto;

public class SuggestImages {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_suggest_images.images_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private Long imagesId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_suggest_images.suggest_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private Long suggestId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_suggest_images.image1
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String image1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_suggest_images.image2
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String image2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_suggest_images.image3
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String image3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_suggest_images.image4
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String image4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_suggest_images.image5
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String image5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_suggest_images.image6
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String image6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_suggest_images.image7
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String image7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_suggest_images.image8
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String image8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_suggest_images.image9
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String image9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_suggest_images.image10
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private String image10;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_suggest_images.images_id
	 * @return  the value of hmdm_pt_suggest_images.images_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public Long getImagesId() {
		return imagesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_suggest_images.images_id
	 * @param imagesId  the value for hmdm_pt_suggest_images.images_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setImagesId(Long imagesId) {
		this.imagesId = imagesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_suggest_images.suggest_id
	 * @return  the value of hmdm_pt_suggest_images.suggest_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public Long getSuggestId() {
		return suggestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_suggest_images.suggest_id
	 * @param suggestId  the value for hmdm_pt_suggest_images.suggest_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setSuggestId(Long suggestId) {
		this.suggestId = suggestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_suggest_images.image1
	 * @return  the value of hmdm_pt_suggest_images.image1
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getImage1() {
		return image1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_suggest_images.image1
	 * @param image1  the value for hmdm_pt_suggest_images.image1
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setImage1(String image1) {
		this.image1 = image1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_suggest_images.image2
	 * @return  the value of hmdm_pt_suggest_images.image2
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getImage2() {
		return image2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_suggest_images.image2
	 * @param image2  the value for hmdm_pt_suggest_images.image2
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setImage2(String image2) {
		this.image2 = image2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_suggest_images.image3
	 * @return  the value of hmdm_pt_suggest_images.image3
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getImage3() {
		return image3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_suggest_images.image3
	 * @param image3  the value for hmdm_pt_suggest_images.image3
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setImage3(String image3) {
		this.image3 = image3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_suggest_images.image4
	 * @return  the value of hmdm_pt_suggest_images.image4
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getImage4() {
		return image4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_suggest_images.image4
	 * @param image4  the value for hmdm_pt_suggest_images.image4
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setImage4(String image4) {
		this.image4 = image4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_suggest_images.image5
	 * @return  the value of hmdm_pt_suggest_images.image5
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getImage5() {
		return image5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_suggest_images.image5
	 * @param image5  the value for hmdm_pt_suggest_images.image5
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setImage5(String image5) {
		this.image5 = image5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_suggest_images.image6
	 * @return  the value of hmdm_pt_suggest_images.image6
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getImage6() {
		return image6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_suggest_images.image6
	 * @param image6  the value for hmdm_pt_suggest_images.image6
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setImage6(String image6) {
		this.image6 = image6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_suggest_images.image7
	 * @return  the value of hmdm_pt_suggest_images.image7
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getImage7() {
		return image7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_suggest_images.image7
	 * @param image7  the value for hmdm_pt_suggest_images.image7
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setImage7(String image7) {
		this.image7 = image7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_suggest_images.image8
	 * @return  the value of hmdm_pt_suggest_images.image8
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getImage8() {
		return image8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_suggest_images.image8
	 * @param image8  the value for hmdm_pt_suggest_images.image8
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setImage8(String image8) {
		this.image8 = image8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_suggest_images.image9
	 * @return  the value of hmdm_pt_suggest_images.image9
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getImage9() {
		return image9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_suggest_images.image9
	 * @param image9  the value for hmdm_pt_suggest_images.image9
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setImage9(String image9) {
		this.image9 = image9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_suggest_images.image10
	 * @return  the value of hmdm_pt_suggest_images.image10
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getImage10() {
		return image10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_suggest_images.image10
	 * @param image10  the value for hmdm_pt_suggest_images.image10
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setImage10(String image10) {
		this.image10 = image10;
	}
}