package hmdm.dto;

public class SuggestInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmdm_pt_suggest_info.suggest_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    private Long suggestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmdm_pt_suggest_info.function_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    private Long functionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmdm_pt_suggest_info.suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    private String suggestInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmdm_pt_suggest_info.suggest_file
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    private String suggestFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmdm_pt_suggest_info.process_instance_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    private String processInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmdm_pt_suggest_info.customer_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    private Long customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmdm_pt_suggest_info.suggest_id
     *
     * @return the value of hmdm_pt_suggest_info.suggest_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public Long getSuggestId() {
        return suggestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmdm_pt_suggest_info.suggest_id
     *
     * @param suggestId the value for hmdm_pt_suggest_info.suggest_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setSuggestId(Long suggestId) {
        this.suggestId = suggestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmdm_pt_suggest_info.function_id
     *
     * @return the value of hmdm_pt_suggest_info.function_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public Long getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmdm_pt_suggest_info.function_id
     *
     * @param functionId the value for hmdm_pt_suggest_info.function_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setFunctionId(Long functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmdm_pt_suggest_info.suggest_info
     *
     * @return the value of hmdm_pt_suggest_info.suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public String getSuggestInfo() {
        return suggestInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmdm_pt_suggest_info.suggest_info
     *
     * @param suggestInfo the value for hmdm_pt_suggest_info.suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setSuggestInfo(String suggestInfo) {
        this.suggestInfo = suggestInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmdm_pt_suggest_info.suggest_file
     *
     * @return the value of hmdm_pt_suggest_info.suggest_file
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public String getSuggestFile() {
        return suggestFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmdm_pt_suggest_info.suggest_file
     *
     * @param suggestFile the value for hmdm_pt_suggest_info.suggest_file
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setSuggestFile(String suggestFile) {
        this.suggestFile = suggestFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmdm_pt_suggest_info.process_instance_id
     *
     * @return the value of hmdm_pt_suggest_info.process_instance_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmdm_pt_suggest_info.process_instance_id
     *
     * @param processInstanceId the value for hmdm_pt_suggest_info.process_instance_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmdm_pt_suggest_info.customer_id
     *
     * @return the value of hmdm_pt_suggest_info.customer_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmdm_pt_suggest_info.customer_id
     *
     * @param customerId the value for hmdm_pt_suggest_info.customer_id
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    @Override
    public String toString() {
        return "SuggestInfo{" +
                "suggestId=" + suggestId +
                ", functionId=" + functionId +
                ", suggestInfo='" + suggestInfo + '\'' +
                ", suggestFile='" + suggestFile + '\'' +
                ", processInstanceId='" + processInstanceId + '\'' +
                ", customerId=" + customerId +
                '}';
    }
}