package hmdm.dto;

import java.util.ArrayList;
import java.util.List;

public class SuggestInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public SuggestInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSuggestIdIsNull() {
            addCriterion("suggest_id is null");
            return (Criteria) this;
        }

        public Criteria andSuggestIdIsNotNull() {
            addCriterion("suggest_id is not null");
            return (Criteria) this;
        }

        public Criteria andSuggestIdEqualTo(Long value) {
            addCriterion("suggest_id =", value, "suggestId");
            return (Criteria) this;
        }

        public Criteria andSuggestIdNotEqualTo(Long value) {
            addCriterion("suggest_id <>", value, "suggestId");
            return (Criteria) this;
        }

        public Criteria andSuggestIdGreaterThan(Long value) {
            addCriterion("suggest_id >", value, "suggestId");
            return (Criteria) this;
        }

        public Criteria andSuggestIdGreaterThanOrEqualTo(Long value) {
            addCriterion("suggest_id >=", value, "suggestId");
            return (Criteria) this;
        }

        public Criteria andSuggestIdLessThan(Long value) {
            addCriterion("suggest_id <", value, "suggestId");
            return (Criteria) this;
        }

        public Criteria andSuggestIdLessThanOrEqualTo(Long value) {
            addCriterion("suggest_id <=", value, "suggestId");
            return (Criteria) this;
        }

        public Criteria andSuggestIdIn(List<Long> values) {
            addCriterion("suggest_id in", values, "suggestId");
            return (Criteria) this;
        }

        public Criteria andSuggestIdNotIn(List<Long> values) {
            addCriterion("suggest_id not in", values, "suggestId");
            return (Criteria) this;
        }

        public Criteria andSuggestIdBetween(Long value1, Long value2) {
            addCriterion("suggest_id between", value1, value2, "suggestId");
            return (Criteria) this;
        }

        public Criteria andSuggestIdNotBetween(Long value1, Long value2) {
            addCriterion("suggest_id not between", value1, value2, "suggestId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdIsNull() {
            addCriterion("function_id is null");
            return (Criteria) this;
        }

        public Criteria andFunctionIdIsNotNull() {
            addCriterion("function_id is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionIdEqualTo(Long value) {
            addCriterion("function_id =", value, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdNotEqualTo(Long value) {
            addCriterion("function_id <>", value, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdGreaterThan(Long value) {
            addCriterion("function_id >", value, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdGreaterThanOrEqualTo(Long value) {
            addCriterion("function_id >=", value, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdLessThan(Long value) {
            addCriterion("function_id <", value, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdLessThanOrEqualTo(Long value) {
            addCriterion("function_id <=", value, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdIn(List<Long> values) {
            addCriterion("function_id in", values, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdNotIn(List<Long> values) {
            addCriterion("function_id not in", values, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdBetween(Long value1, Long value2) {
            addCriterion("function_id between", value1, value2, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdNotBetween(Long value1, Long value2) {
            addCriterion("function_id not between", value1, value2, "functionId");
            return (Criteria) this;
        }

        public Criteria andSuggestInfoIsNull() {
            addCriterion("suggest_info is null");
            return (Criteria) this;
        }

        public Criteria andSuggestInfoIsNotNull() {
            addCriterion("suggest_info is not null");
            return (Criteria) this;
        }

        public Criteria andSuggestInfoEqualTo(String value) {
            addCriterion("suggest_info =", value, "suggestInfo");
            return (Criteria) this;
        }

        public Criteria andSuggestInfoNotEqualTo(String value) {
            addCriterion("suggest_info <>", value, "suggestInfo");
            return (Criteria) this;
        }

        public Criteria andSuggestInfoGreaterThan(String value) {
            addCriterion("suggest_info >", value, "suggestInfo");
            return (Criteria) this;
        }

        public Criteria andSuggestInfoGreaterThanOrEqualTo(String value) {
            addCriterion("suggest_info >=", value, "suggestInfo");
            return (Criteria) this;
        }

        public Criteria andSuggestInfoLessThan(String value) {
            addCriterion("suggest_info <", value, "suggestInfo");
            return (Criteria) this;
        }

        public Criteria andSuggestInfoLessThanOrEqualTo(String value) {
            addCriterion("suggest_info <=", value, "suggestInfo");
            return (Criteria) this;
        }

        public Criteria andSuggestInfoLike(String value) {
            addCriterion("suggest_info like", value, "suggestInfo");
            return (Criteria) this;
        }

        public Criteria andSuggestInfoNotLike(String value) {
            addCriterion("suggest_info not like", value, "suggestInfo");
            return (Criteria) this;
        }

        public Criteria andSuggestInfoIn(List<String> values) {
            addCriterion("suggest_info in", values, "suggestInfo");
            return (Criteria) this;
        }

        public Criteria andSuggestInfoNotIn(List<String> values) {
            addCriterion("suggest_info not in", values, "suggestInfo");
            return (Criteria) this;
        }

        public Criteria andSuggestInfoBetween(String value1, String value2) {
            addCriterion("suggest_info between", value1, value2, "suggestInfo");
            return (Criteria) this;
        }

        public Criteria andSuggestInfoNotBetween(String value1, String value2) {
            addCriterion("suggest_info not between", value1, value2, "suggestInfo");
            return (Criteria) this;
        }

        public Criteria andSuggestFileIsNull() {
            addCriterion("suggest_file is null");
            return (Criteria) this;
        }

        public Criteria andSuggestFileIsNotNull() {
            addCriterion("suggest_file is not null");
            return (Criteria) this;
        }

        public Criteria andSuggestFileEqualTo(String value) {
            addCriterion("suggest_file =", value, "suggestFile");
            return (Criteria) this;
        }

        public Criteria andSuggestFileNotEqualTo(String value) {
            addCriterion("suggest_file <>", value, "suggestFile");
            return (Criteria) this;
        }

        public Criteria andSuggestFileGreaterThan(String value) {
            addCriterion("suggest_file >", value, "suggestFile");
            return (Criteria) this;
        }

        public Criteria andSuggestFileGreaterThanOrEqualTo(String value) {
            addCriterion("suggest_file >=", value, "suggestFile");
            return (Criteria) this;
        }

        public Criteria andSuggestFileLessThan(String value) {
            addCriterion("suggest_file <", value, "suggestFile");
            return (Criteria) this;
        }

        public Criteria andSuggestFileLessThanOrEqualTo(String value) {
            addCriterion("suggest_file <=", value, "suggestFile");
            return (Criteria) this;
        }

        public Criteria andSuggestFileLike(String value) {
            addCriterion("suggest_file like", value, "suggestFile");
            return (Criteria) this;
        }

        public Criteria andSuggestFileNotLike(String value) {
            addCriterion("suggest_file not like", value, "suggestFile");
            return (Criteria) this;
        }

        public Criteria andSuggestFileIn(List<String> values) {
            addCriterion("suggest_file in", values, "suggestFile");
            return (Criteria) this;
        }

        public Criteria andSuggestFileNotIn(List<String> values) {
            addCriterion("suggest_file not in", values, "suggestFile");
            return (Criteria) this;
        }

        public Criteria andSuggestFileBetween(String value1, String value2) {
            addCriterion("suggest_file between", value1, value2, "suggestFile");
            return (Criteria) this;
        }

        public Criteria andSuggestFileNotBetween(String value1, String value2) {
            addCriterion("suggest_file not between", value1, value2, "suggestFile");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIdIsNull() {
            addCriterion("process_instance_id is null");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIdIsNotNull() {
            addCriterion("process_instance_id is not null");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIdEqualTo(String value) {
            addCriterion("process_instance_id =", value, "processInstanceId");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIdNotEqualTo(String value) {
            addCriterion("process_instance_id <>", value, "processInstanceId");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIdGreaterThan(String value) {
            addCriterion("process_instance_id >", value, "processInstanceId");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIdGreaterThanOrEqualTo(String value) {
            addCriterion("process_instance_id >=", value, "processInstanceId");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIdLessThan(String value) {
            addCriterion("process_instance_id <", value, "processInstanceId");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIdLessThanOrEqualTo(String value) {
            addCriterion("process_instance_id <=", value, "processInstanceId");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIdLike(String value) {
            addCriterion("process_instance_id like", value, "processInstanceId");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIdNotLike(String value) {
            addCriterion("process_instance_id not like", value, "processInstanceId");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIdIn(List<String> values) {
            addCriterion("process_instance_id in", values, "processInstanceId");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIdNotIn(List<String> values) {
            addCriterion("process_instance_id not in", values, "processInstanceId");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIdBetween(String value1, String value2) {
            addCriterion("process_instance_id between", value1, value2, "processInstanceId");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIdNotBetween(String value1, String value2) {
            addCriterion("process_instance_id not between", value1, value2, "processInstanceId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(Long value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(Long value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(Long value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(Long value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(Long value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<Long> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<Long> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(Long value1, Long value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(Long value1, Long value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hmdm_pt_suggest_info
     *
     * @mbg.generated Thu Aug 10 15:25:14 GMT+08:00 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}