package hmdm.dto;

import java.util.ArrayList;
import java.util.List;

public class SuggestImagesExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public SuggestImagesExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andImagesIdIsNull() {
			addCriterion("images_id is null");
			return (Criteria) this;
		}

		public Criteria andImagesIdIsNotNull() {
			addCriterion("images_id is not null");
			return (Criteria) this;
		}

		public Criteria andImagesIdEqualTo(Long value) {
			addCriterion("images_id =", value, "imagesId");
			return (Criteria) this;
		}

		public Criteria andImagesIdNotEqualTo(Long value) {
			addCriterion("images_id <>", value, "imagesId");
			return (Criteria) this;
		}

		public Criteria andImagesIdGreaterThan(Long value) {
			addCriterion("images_id >", value, "imagesId");
			return (Criteria) this;
		}

		public Criteria andImagesIdGreaterThanOrEqualTo(Long value) {
			addCriterion("images_id >=", value, "imagesId");
			return (Criteria) this;
		}

		public Criteria andImagesIdLessThan(Long value) {
			addCriterion("images_id <", value, "imagesId");
			return (Criteria) this;
		}

		public Criteria andImagesIdLessThanOrEqualTo(Long value) {
			addCriterion("images_id <=", value, "imagesId");
			return (Criteria) this;
		}

		public Criteria andImagesIdIn(List<Long> values) {
			addCriterion("images_id in", values, "imagesId");
			return (Criteria) this;
		}

		public Criteria andImagesIdNotIn(List<Long> values) {
			addCriterion("images_id not in", values, "imagesId");
			return (Criteria) this;
		}

		public Criteria andImagesIdBetween(Long value1, Long value2) {
			addCriterion("images_id between", value1, value2, "imagesId");
			return (Criteria) this;
		}

		public Criteria andImagesIdNotBetween(Long value1, Long value2) {
			addCriterion("images_id not between", value1, value2, "imagesId");
			return (Criteria) this;
		}

		public Criteria andSuggestIdIsNull() {
			addCriterion("suggest_id is null");
			return (Criteria) this;
		}

		public Criteria andSuggestIdIsNotNull() {
			addCriterion("suggest_id is not null");
			return (Criteria) this;
		}

		public Criteria andSuggestIdEqualTo(Long value) {
			addCriterion("suggest_id =", value, "suggestId");
			return (Criteria) this;
		}

		public Criteria andSuggestIdNotEqualTo(Long value) {
			addCriterion("suggest_id <>", value, "suggestId");
			return (Criteria) this;
		}

		public Criteria andSuggestIdGreaterThan(Long value) {
			addCriterion("suggest_id >", value, "suggestId");
			return (Criteria) this;
		}

		public Criteria andSuggestIdGreaterThanOrEqualTo(Long value) {
			addCriterion("suggest_id >=", value, "suggestId");
			return (Criteria) this;
		}

		public Criteria andSuggestIdLessThan(Long value) {
			addCriterion("suggest_id <", value, "suggestId");
			return (Criteria) this;
		}

		public Criteria andSuggestIdLessThanOrEqualTo(Long value) {
			addCriterion("suggest_id <=", value, "suggestId");
			return (Criteria) this;
		}

		public Criteria andSuggestIdIn(List<Long> values) {
			addCriterion("suggest_id in", values, "suggestId");
			return (Criteria) this;
		}

		public Criteria andSuggestIdNotIn(List<Long> values) {
			addCriterion("suggest_id not in", values, "suggestId");
			return (Criteria) this;
		}

		public Criteria andSuggestIdBetween(Long value1, Long value2) {
			addCriterion("suggest_id between", value1, value2, "suggestId");
			return (Criteria) this;
		}

		public Criteria andSuggestIdNotBetween(Long value1, Long value2) {
			addCriterion("suggest_id not between", value1, value2, "suggestId");
			return (Criteria) this;
		}

		public Criteria andImage1IsNull() {
			addCriterion("image1 is null");
			return (Criteria) this;
		}

		public Criteria andImage1IsNotNull() {
			addCriterion("image1 is not null");
			return (Criteria) this;
		}

		public Criteria andImage1EqualTo(String value) {
			addCriterion("image1 =", value, "image1");
			return (Criteria) this;
		}

		public Criteria andImage1NotEqualTo(String value) {
			addCriterion("image1 <>", value, "image1");
			return (Criteria) this;
		}

		public Criteria andImage1GreaterThan(String value) {
			addCriterion("image1 >", value, "image1");
			return (Criteria) this;
		}

		public Criteria andImage1GreaterThanOrEqualTo(String value) {
			addCriterion("image1 >=", value, "image1");
			return (Criteria) this;
		}

		public Criteria andImage1LessThan(String value) {
			addCriterion("image1 <", value, "image1");
			return (Criteria) this;
		}

		public Criteria andImage1LessThanOrEqualTo(String value) {
			addCriterion("image1 <=", value, "image1");
			return (Criteria) this;
		}

		public Criteria andImage1Like(String value) {
			addCriterion("image1 like", value, "image1");
			return (Criteria) this;
		}

		public Criteria andImage1NotLike(String value) {
			addCriterion("image1 not like", value, "image1");
			return (Criteria) this;
		}

		public Criteria andImage1In(List<String> values) {
			addCriterion("image1 in", values, "image1");
			return (Criteria) this;
		}

		public Criteria andImage1NotIn(List<String> values) {
			addCriterion("image1 not in", values, "image1");
			return (Criteria) this;
		}

		public Criteria andImage1Between(String value1, String value2) {
			addCriterion("image1 between", value1, value2, "image1");
			return (Criteria) this;
		}

		public Criteria andImage1NotBetween(String value1, String value2) {
			addCriterion("image1 not between", value1, value2, "image1");
			return (Criteria) this;
		}

		public Criteria andImage2IsNull() {
			addCriterion("image2 is null");
			return (Criteria) this;
		}

		public Criteria andImage2IsNotNull() {
			addCriterion("image2 is not null");
			return (Criteria) this;
		}

		public Criteria andImage2EqualTo(String value) {
			addCriterion("image2 =", value, "image2");
			return (Criteria) this;
		}

		public Criteria andImage2NotEqualTo(String value) {
			addCriterion("image2 <>", value, "image2");
			return (Criteria) this;
		}

		public Criteria andImage2GreaterThan(String value) {
			addCriterion("image2 >", value, "image2");
			return (Criteria) this;
		}

		public Criteria andImage2GreaterThanOrEqualTo(String value) {
			addCriterion("image2 >=", value, "image2");
			return (Criteria) this;
		}

		public Criteria andImage2LessThan(String value) {
			addCriterion("image2 <", value, "image2");
			return (Criteria) this;
		}

		public Criteria andImage2LessThanOrEqualTo(String value) {
			addCriterion("image2 <=", value, "image2");
			return (Criteria) this;
		}

		public Criteria andImage2Like(String value) {
			addCriterion("image2 like", value, "image2");
			return (Criteria) this;
		}

		public Criteria andImage2NotLike(String value) {
			addCriterion("image2 not like", value, "image2");
			return (Criteria) this;
		}

		public Criteria andImage2In(List<String> values) {
			addCriterion("image2 in", values, "image2");
			return (Criteria) this;
		}

		public Criteria andImage2NotIn(List<String> values) {
			addCriterion("image2 not in", values, "image2");
			return (Criteria) this;
		}

		public Criteria andImage2Between(String value1, String value2) {
			addCriterion("image2 between", value1, value2, "image2");
			return (Criteria) this;
		}

		public Criteria andImage2NotBetween(String value1, String value2) {
			addCriterion("image2 not between", value1, value2, "image2");
			return (Criteria) this;
		}

		public Criteria andImage3IsNull() {
			addCriterion("image3 is null");
			return (Criteria) this;
		}

		public Criteria andImage3IsNotNull() {
			addCriterion("image3 is not null");
			return (Criteria) this;
		}

		public Criteria andImage3EqualTo(String value) {
			addCriterion("image3 =", value, "image3");
			return (Criteria) this;
		}

		public Criteria andImage3NotEqualTo(String value) {
			addCriterion("image3 <>", value, "image3");
			return (Criteria) this;
		}

		public Criteria andImage3GreaterThan(String value) {
			addCriterion("image3 >", value, "image3");
			return (Criteria) this;
		}

		public Criteria andImage3GreaterThanOrEqualTo(String value) {
			addCriterion("image3 >=", value, "image3");
			return (Criteria) this;
		}

		public Criteria andImage3LessThan(String value) {
			addCriterion("image3 <", value, "image3");
			return (Criteria) this;
		}

		public Criteria andImage3LessThanOrEqualTo(String value) {
			addCriterion("image3 <=", value, "image3");
			return (Criteria) this;
		}

		public Criteria andImage3Like(String value) {
			addCriterion("image3 like", value, "image3");
			return (Criteria) this;
		}

		public Criteria andImage3NotLike(String value) {
			addCriterion("image3 not like", value, "image3");
			return (Criteria) this;
		}

		public Criteria andImage3In(List<String> values) {
			addCriterion("image3 in", values, "image3");
			return (Criteria) this;
		}

		public Criteria andImage3NotIn(List<String> values) {
			addCriterion("image3 not in", values, "image3");
			return (Criteria) this;
		}

		public Criteria andImage3Between(String value1, String value2) {
			addCriterion("image3 between", value1, value2, "image3");
			return (Criteria) this;
		}

		public Criteria andImage3NotBetween(String value1, String value2) {
			addCriterion("image3 not between", value1, value2, "image3");
			return (Criteria) this;
		}

		public Criteria andImage4IsNull() {
			addCriterion("image4 is null");
			return (Criteria) this;
		}

		public Criteria andImage4IsNotNull() {
			addCriterion("image4 is not null");
			return (Criteria) this;
		}

		public Criteria andImage4EqualTo(String value) {
			addCriterion("image4 =", value, "image4");
			return (Criteria) this;
		}

		public Criteria andImage4NotEqualTo(String value) {
			addCriterion("image4 <>", value, "image4");
			return (Criteria) this;
		}

		public Criteria andImage4GreaterThan(String value) {
			addCriterion("image4 >", value, "image4");
			return (Criteria) this;
		}

		public Criteria andImage4GreaterThanOrEqualTo(String value) {
			addCriterion("image4 >=", value, "image4");
			return (Criteria) this;
		}

		public Criteria andImage4LessThan(String value) {
			addCriterion("image4 <", value, "image4");
			return (Criteria) this;
		}

		public Criteria andImage4LessThanOrEqualTo(String value) {
			addCriterion("image4 <=", value, "image4");
			return (Criteria) this;
		}

		public Criteria andImage4Like(String value) {
			addCriterion("image4 like", value, "image4");
			return (Criteria) this;
		}

		public Criteria andImage4NotLike(String value) {
			addCriterion("image4 not like", value, "image4");
			return (Criteria) this;
		}

		public Criteria andImage4In(List<String> values) {
			addCriterion("image4 in", values, "image4");
			return (Criteria) this;
		}

		public Criteria andImage4NotIn(List<String> values) {
			addCriterion("image4 not in", values, "image4");
			return (Criteria) this;
		}

		public Criteria andImage4Between(String value1, String value2) {
			addCriterion("image4 between", value1, value2, "image4");
			return (Criteria) this;
		}

		public Criteria andImage4NotBetween(String value1, String value2) {
			addCriterion("image4 not between", value1, value2, "image4");
			return (Criteria) this;
		}

		public Criteria andImage5IsNull() {
			addCriterion("image5 is null");
			return (Criteria) this;
		}

		public Criteria andImage5IsNotNull() {
			addCriterion("image5 is not null");
			return (Criteria) this;
		}

		public Criteria andImage5EqualTo(String value) {
			addCriterion("image5 =", value, "image5");
			return (Criteria) this;
		}

		public Criteria andImage5NotEqualTo(String value) {
			addCriterion("image5 <>", value, "image5");
			return (Criteria) this;
		}

		public Criteria andImage5GreaterThan(String value) {
			addCriterion("image5 >", value, "image5");
			return (Criteria) this;
		}

		public Criteria andImage5GreaterThanOrEqualTo(String value) {
			addCriterion("image5 >=", value, "image5");
			return (Criteria) this;
		}

		public Criteria andImage5LessThan(String value) {
			addCriterion("image5 <", value, "image5");
			return (Criteria) this;
		}

		public Criteria andImage5LessThanOrEqualTo(String value) {
			addCriterion("image5 <=", value, "image5");
			return (Criteria) this;
		}

		public Criteria andImage5Like(String value) {
			addCriterion("image5 like", value, "image5");
			return (Criteria) this;
		}

		public Criteria andImage5NotLike(String value) {
			addCriterion("image5 not like", value, "image5");
			return (Criteria) this;
		}

		public Criteria andImage5In(List<String> values) {
			addCriterion("image5 in", values, "image5");
			return (Criteria) this;
		}

		public Criteria andImage5NotIn(List<String> values) {
			addCriterion("image5 not in", values, "image5");
			return (Criteria) this;
		}

		public Criteria andImage5Between(String value1, String value2) {
			addCriterion("image5 between", value1, value2, "image5");
			return (Criteria) this;
		}

		public Criteria andImage5NotBetween(String value1, String value2) {
			addCriterion("image5 not between", value1, value2, "image5");
			return (Criteria) this;
		}

		public Criteria andImage6IsNull() {
			addCriterion("image6 is null");
			return (Criteria) this;
		}

		public Criteria andImage6IsNotNull() {
			addCriterion("image6 is not null");
			return (Criteria) this;
		}

		public Criteria andImage6EqualTo(String value) {
			addCriterion("image6 =", value, "image6");
			return (Criteria) this;
		}

		public Criteria andImage6NotEqualTo(String value) {
			addCriterion("image6 <>", value, "image6");
			return (Criteria) this;
		}

		public Criteria andImage6GreaterThan(String value) {
			addCriterion("image6 >", value, "image6");
			return (Criteria) this;
		}

		public Criteria andImage6GreaterThanOrEqualTo(String value) {
			addCriterion("image6 >=", value, "image6");
			return (Criteria) this;
		}

		public Criteria andImage6LessThan(String value) {
			addCriterion("image6 <", value, "image6");
			return (Criteria) this;
		}

		public Criteria andImage6LessThanOrEqualTo(String value) {
			addCriterion("image6 <=", value, "image6");
			return (Criteria) this;
		}

		public Criteria andImage6Like(String value) {
			addCriterion("image6 like", value, "image6");
			return (Criteria) this;
		}

		public Criteria andImage6NotLike(String value) {
			addCriterion("image6 not like", value, "image6");
			return (Criteria) this;
		}

		public Criteria andImage6In(List<String> values) {
			addCriterion("image6 in", values, "image6");
			return (Criteria) this;
		}

		public Criteria andImage6NotIn(List<String> values) {
			addCriterion("image6 not in", values, "image6");
			return (Criteria) this;
		}

		public Criteria andImage6Between(String value1, String value2) {
			addCriterion("image6 between", value1, value2, "image6");
			return (Criteria) this;
		}

		public Criteria andImage6NotBetween(String value1, String value2) {
			addCriterion("image6 not between", value1, value2, "image6");
			return (Criteria) this;
		}

		public Criteria andImage7IsNull() {
			addCriterion("image7 is null");
			return (Criteria) this;
		}

		public Criteria andImage7IsNotNull() {
			addCriterion("image7 is not null");
			return (Criteria) this;
		}

		public Criteria andImage7EqualTo(String value) {
			addCriterion("image7 =", value, "image7");
			return (Criteria) this;
		}

		public Criteria andImage7NotEqualTo(String value) {
			addCriterion("image7 <>", value, "image7");
			return (Criteria) this;
		}

		public Criteria andImage7GreaterThan(String value) {
			addCriterion("image7 >", value, "image7");
			return (Criteria) this;
		}

		public Criteria andImage7GreaterThanOrEqualTo(String value) {
			addCriterion("image7 >=", value, "image7");
			return (Criteria) this;
		}

		public Criteria andImage7LessThan(String value) {
			addCriterion("image7 <", value, "image7");
			return (Criteria) this;
		}

		public Criteria andImage7LessThanOrEqualTo(String value) {
			addCriterion("image7 <=", value, "image7");
			return (Criteria) this;
		}

		public Criteria andImage7Like(String value) {
			addCriterion("image7 like", value, "image7");
			return (Criteria) this;
		}

		public Criteria andImage7NotLike(String value) {
			addCriterion("image7 not like", value, "image7");
			return (Criteria) this;
		}

		public Criteria andImage7In(List<String> values) {
			addCriterion("image7 in", values, "image7");
			return (Criteria) this;
		}

		public Criteria andImage7NotIn(List<String> values) {
			addCriterion("image7 not in", values, "image7");
			return (Criteria) this;
		}

		public Criteria andImage7Between(String value1, String value2) {
			addCriterion("image7 between", value1, value2, "image7");
			return (Criteria) this;
		}

		public Criteria andImage7NotBetween(String value1, String value2) {
			addCriterion("image7 not between", value1, value2, "image7");
			return (Criteria) this;
		}

		public Criteria andImage8IsNull() {
			addCriterion("image8 is null");
			return (Criteria) this;
		}

		public Criteria andImage8IsNotNull() {
			addCriterion("image8 is not null");
			return (Criteria) this;
		}

		public Criteria andImage8EqualTo(String value) {
			addCriterion("image8 =", value, "image8");
			return (Criteria) this;
		}

		public Criteria andImage8NotEqualTo(String value) {
			addCriterion("image8 <>", value, "image8");
			return (Criteria) this;
		}

		public Criteria andImage8GreaterThan(String value) {
			addCriterion("image8 >", value, "image8");
			return (Criteria) this;
		}

		public Criteria andImage8GreaterThanOrEqualTo(String value) {
			addCriterion("image8 >=", value, "image8");
			return (Criteria) this;
		}

		public Criteria andImage8LessThan(String value) {
			addCriterion("image8 <", value, "image8");
			return (Criteria) this;
		}

		public Criteria andImage8LessThanOrEqualTo(String value) {
			addCriterion("image8 <=", value, "image8");
			return (Criteria) this;
		}

		public Criteria andImage8Like(String value) {
			addCriterion("image8 like", value, "image8");
			return (Criteria) this;
		}

		public Criteria andImage8NotLike(String value) {
			addCriterion("image8 not like", value, "image8");
			return (Criteria) this;
		}

		public Criteria andImage8In(List<String> values) {
			addCriterion("image8 in", values, "image8");
			return (Criteria) this;
		}

		public Criteria andImage8NotIn(List<String> values) {
			addCriterion("image8 not in", values, "image8");
			return (Criteria) this;
		}

		public Criteria andImage8Between(String value1, String value2) {
			addCriterion("image8 between", value1, value2, "image8");
			return (Criteria) this;
		}

		public Criteria andImage8NotBetween(String value1, String value2) {
			addCriterion("image8 not between", value1, value2, "image8");
			return (Criteria) this;
		}

		public Criteria andImage9IsNull() {
			addCriterion("image9 is null");
			return (Criteria) this;
		}

		public Criteria andImage9IsNotNull() {
			addCriterion("image9 is not null");
			return (Criteria) this;
		}

		public Criteria andImage9EqualTo(String value) {
			addCriterion("image9 =", value, "image9");
			return (Criteria) this;
		}

		public Criteria andImage9NotEqualTo(String value) {
			addCriterion("image9 <>", value, "image9");
			return (Criteria) this;
		}

		public Criteria andImage9GreaterThan(String value) {
			addCriterion("image9 >", value, "image9");
			return (Criteria) this;
		}

		public Criteria andImage9GreaterThanOrEqualTo(String value) {
			addCriterion("image9 >=", value, "image9");
			return (Criteria) this;
		}

		public Criteria andImage9LessThan(String value) {
			addCriterion("image9 <", value, "image9");
			return (Criteria) this;
		}

		public Criteria andImage9LessThanOrEqualTo(String value) {
			addCriterion("image9 <=", value, "image9");
			return (Criteria) this;
		}

		public Criteria andImage9Like(String value) {
			addCriterion("image9 like", value, "image9");
			return (Criteria) this;
		}

		public Criteria andImage9NotLike(String value) {
			addCriterion("image9 not like", value, "image9");
			return (Criteria) this;
		}

		public Criteria andImage9In(List<String> values) {
			addCriterion("image9 in", values, "image9");
			return (Criteria) this;
		}

		public Criteria andImage9NotIn(List<String> values) {
			addCriterion("image9 not in", values, "image9");
			return (Criteria) this;
		}

		public Criteria andImage9Between(String value1, String value2) {
			addCriterion("image9 between", value1, value2, "image9");
			return (Criteria) this;
		}

		public Criteria andImage9NotBetween(String value1, String value2) {
			addCriterion("image9 not between", value1, value2, "image9");
			return (Criteria) this;
		}

		public Criteria andImage10IsNull() {
			addCriterion("image10 is null");
			return (Criteria) this;
		}

		public Criteria andImage10IsNotNull() {
			addCriterion("image10 is not null");
			return (Criteria) this;
		}

		public Criteria andImage10EqualTo(String value) {
			addCriterion("image10 =", value, "image10");
			return (Criteria) this;
		}

		public Criteria andImage10NotEqualTo(String value) {
			addCriterion("image10 <>", value, "image10");
			return (Criteria) this;
		}

		public Criteria andImage10GreaterThan(String value) {
			addCriterion("image10 >", value, "image10");
			return (Criteria) this;
		}

		public Criteria andImage10GreaterThanOrEqualTo(String value) {
			addCriterion("image10 >=", value, "image10");
			return (Criteria) this;
		}

		public Criteria andImage10LessThan(String value) {
			addCriterion("image10 <", value, "image10");
			return (Criteria) this;
		}

		public Criteria andImage10LessThanOrEqualTo(String value) {
			addCriterion("image10 <=", value, "image10");
			return (Criteria) this;
		}

		public Criteria andImage10Like(String value) {
			addCriterion("image10 like", value, "image10");
			return (Criteria) this;
		}

		public Criteria andImage10NotLike(String value) {
			addCriterion("image10 not like", value, "image10");
			return (Criteria) this;
		}

		public Criteria andImage10In(List<String> values) {
			addCriterion("image10 in", values, "image10");
			return (Criteria) this;
		}

		public Criteria andImage10NotIn(List<String> values) {
			addCriterion("image10 not in", values, "image10");
			return (Criteria) this;
		}

		public Criteria andImage10Between(String value1, String value2) {
			addCriterion("image10 between", value1, value2, "image10");
			return (Criteria) this;
		}

		public Criteria andImage10NotBetween(String value1, String value2) {
			addCriterion("image10 not between", value1, value2, "image10");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hmdm_pt_suggest_images
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hmdm_pt_suggest_images
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 09 11:39:48 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}