package hmdm.dto;

public class UserRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_user_role.user_role_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private Integer userRoleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_user_role.user_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hmdm_pt_user_role.role_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	private Integer roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_user_role.user_role_id
	 * @return  the value of hmdm_pt_user_role.user_role_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public Integer getUserRoleId() {
		return userRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_user_role.user_role_id
	 * @param userRoleId  the value for hmdm_pt_user_role.user_role_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setUserRoleId(Integer userRoleId) {
		this.userRoleId = userRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_user_role.user_id
	 * @return  the value of hmdm_pt_user_role.user_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_user_role.user_id
	 * @param userId  the value for hmdm_pt_user_role.user_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hmdm_pt_user_role.role_id
	 * @return  the value of hmdm_pt_user_role.role_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hmdm_pt_user_role.role_id
	 * @param roleId  the value for hmdm_pt_user_role.role_id
	 * @mbg.generated  Wed Aug 09 11:45:39 GMT+08:00 2017
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}
}